[project]
name = "triage"
version = "0.1.0"
description = "Triage a personal inbox of documents."
authors = [{ name = "Benjamin Rothan" }]
requires-python = ">=3.10"
dependencies = [
    "click==8.3.0",
    "markdown-it-py==4.0.0",
    "mdurl==0.1.2",
    "prompt-toolkit==3.0.52",
    "pygments==2.19.2",
    "rich==14.2.0",
    "shellingham==1.5.4",
    "typer==0.19.2",
    "typing-extensions==4.15.0",
    "wcwidth==0.2.14",
]

[project.scripts]
triage = "triage.cli:app"

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
